name: simple

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - ubuntu-20.04-ppc64le

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo Hello, world!
          sleep 15
          echo Goodbye!
